# -*- coding: utf-8 -*-
"""DATA301Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZjSlEKio19RDSA0lPjQ2R3WhI8ILoqt1

**DATA301 Project Notebook**

**Research Question 1: What variables are associated with the validity of a statement**

Descriptions of each variable in our logistic regression model, after manipulation:
1. **Classification**: (Categorical,Response) The validity of a statement. Grouped as True, Half-True, False.

2. **Occupation***: (Categorical,Explanatory) The occupation of the speaker responsible for the statement. Grouped as Government and Non-Government. Baseline is Government.

3. **Context***: (Categorical, Explanatory) The environmental context of where and how the statement was recorded. Grouped into Interview, Speeck, Media, Social Media, and Other. Baseline is Interview.

4. **Topic***: (Cateogrical, Explanatory) A one word decription of the topic of the statement. Grouped into Economy, Healthcare, Immigration, National Security, Foreign Policy, Education, Environment, Social Issues, and Elections/Governance. Baseline is Economy.

5. **Party***: (Categorical, Explanatory) The political party of the speaker. Grouped as Republican, Democrat, and Other. Baseline is Democrat.

6. **False*** (Quantitative, Explanatory) The historical count of the speaker's statements classified as false, that have been recorded in PolitiFact.com

7. **Half-True***: (Quantitative, Explanatory) The historical count of the speaker's statements classified as half-true, that have been recorded in PolitiFact.com

8. **True***: (Quantitative, Explanatory) The historical count of the speaker's statements classified as true, that have been recorded in PolitiFact.com
"""

# libraries
from pandas import *
from sklearn.linear_model import LogisticRegression
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score
from plotnine import *

# Upload the Data sets, train, test, and valid
train = read_csv("train2.tsv", sep="\t",
                 names = ['file','classification','statement','topic','speaker','speaker_job',
                          'speaker_state','speaker_party','barely_t','false','half_t','mostly_t',
                          'total_lie','context','justification'])

test = read_csv("test2.tsv", sep="\t",
                 names = ['file','classification','statement','topic','speaker','speaker_job',
                          'speaker_state','speaker_party','barely_t','false','half_t','mostly_t',
                          'total_lie','context','justification'])
valid = read_csv("val2.tsv", sep="\t",
                 names = ['file','classification','statement','topic','speaker','speaker_job',
                          'speaker_state','speaker_party','barely_t','false','half_t','mostly_t',
                          'total_lie','context','justification'])

# Data is messy, must reduce the categories in explanatory variables
# Function to reduce cats in speaker_job
def group_speaker_job(job):
    if isna(job):
        return "Non-Government"
    job = job.lower()
    if any(x in job for x in ['senator', 'representative', 'congress', 'legislator', 'governor', 'president', 'mayor', 'executive']):
        return "Government"
    else:
        return "Non-Government"
# Function to reduce cats in context var
def group_context(context):
    if isna(context):
        return "Other"
    context = context.lower()
    if any(x in context for x in ['interview', 'interviewee', 'interviewing',]):
        return "Interview"
    elif any(x in context for x in ["speech", "debate","debated", "town hall", "press conference","campaign rally",
                                    "address",'press','forum']):
        return "Speech"
    elif any(x in context for x in ["ad", "advertisement", "commercial", "video",
                                    "film", "media", "article", "book", "novel","podcast", "radio", "tv",
                                    "television","abc","cnn","fox",'show','flier','email']):
        return "Media"
    elif any(x in context for x in ["tweet", "twitter", "facebook", "instagram","social media", "post",
                                    'web', 'internet','blog','op-ed']):
        return "Social_Media"
    else:
        return "Other"

# Topic has many labels - keep only first topic
train['topic'] = train['topic'].str.split(',').str[0]
train["topic"].value_counts()

# Library and Function to reduce cats in topic var
topic_map = {
    "Economy/Fiscal": [
        "economy", "economic", "tax", "budget", "deficit",
        "debt", "trade", "jobs", "employment", "income"
    ],
    "Healthcare": [
        "health", "medicare", "medicaid", "obamacare",
        "insurance", "drug", "hospital"
    ],
    "Immigration": [
        "immigration", "border", "asylum", "refugee"
    ],
    "National Security": [
        "military", "defense", "terror", "security",
        "war", "iraq", "afghanistan"
    ],
    "Foreign Policy": [
        "foreign", "china", "russia", "nato",
        "diplomacy", "international"
    ],
    "Education": [
        "education", "school", "college", "student",
        "tuition"
    ],
    "Environment": [
        "climate", "environment", "energy",
        "oil", "gas", "renewable"
    ],
    "Social Issues": [
        "abortion", "gun", "marriage", "lgbt",
        "religion", "rights"
    ],
    "Elections/Governance": [
        "election", "campaign", "vote",
        "ethics", "transparency", "corruption"
    ]
}

def group_topic(topic):
    if isna(topic):
        return "Other"
    topic = topic.lower()
    for category, keywords in topic_map.items():
        if any(keyword in topic for keyword in keywords):
            return category
    return "Other"
# Function to restrict group party var to just 3 cats
def group_party(party):
  if isna(party):
    return "Other"
  elif any(x in party for x in ['democrat','democratic', 'liberal']):
    return "Democrat"
  elif any(x in party for x in ['republican','republican', 'conservative']):
    return "Republican"
  else:
    return "Other"
# Function to reduce 5 categories in classification into 3: true, half-true, false
def reduce_class(classification):
  x = classification.lower()
  if x in ["pants-fire", "false"]:
    return "False"
  elif x in ["true", "mostly-true"]:
    return "True"
  else:
    return "Half-True"

# Code to create new variables to be used for model
train = concat([train,valid]) # Combine train and valid data
train = train.dropna(subset=["classification"])   # dropped any rows w/ missing classifications (only 2)
train["classification"] = train["classification"].apply(reduce_class) # reducing class categories to 3
train['false*'] = train["false"].fillna(0) + train["total_lie"].fillna(0) # reducing track record categories to 3
train['half_t*'] = train["half_t"].fillna(0)
train['true*'] = train["mostly_t"].fillna(0)
train["statement"] = train["statement"].fillna("")
train["occupation*"] = train["speaker_job"].apply(group_speaker_job)  # job
train["context*"] = train["context"].apply(group_context)             # context
train['topic'] = train['topic'].str.split(',').str[0]                 # topic
train['topic*'] = train['topic'].apply(group_topic)
train['party*'] = train['speaker_party'].apply(group_party)           # party

# Distribution of data not severely unbalanced, so we can consider accuracy as a metric
train["classification"].value_counts()

# Establish Model
model = LogisticRegression(multi_class = 'multinomial') # model

# standardize/onehotencode data
quants = ['false*','half_t*','true*']
cats = ['context*','occupation*','party*','topic*']

preproc = make_column_transformer(
    (OneHotEncoder(drop = "first", handle_unknown = "ignore"),cats),
    (StandardScaler(),quants),
    remainder = 'drop')

# ensureing drop = 'first' creates baseline for category variables

pipe = make_pipeline(preproc,model)

pipe.fit(train[cats+quants],train["classification"])

# Cross Validation on training data to estimate testing error
f1_scores = cross_val_score(pipe,X = train[cats+quants],y = train['classification'],cv = 10,scoring = "f1_macro")
acc_scores = cross_val_score(pipe,X = train[cats+quants],y = train['classification'],cv = 10,scoring = "accuracy")
DataFrame({"F1":[f1_scores.mean()],"Accuracy":[acc_scores.mean()]})

# Grid Search for variables for best parameters and results
from sklearn.model_selection import GridSearchCV

param_grid = {
    "logisticregression__C": [1,5,10,15],
    "logisticregression__solver": ["lbfgs", "saga"],
    "logisticregression__max_iter": [1000,3000,5000]}

grid = GridSearchCV(
    pipe,
    param_grid,
    cv=5,
    scoring="f1_macro")

grid.fit(train[cats + quants], train["classification"])

# Best parameters to use for our log regression model
grid.best_params_

# F1-Score of our best model - metric is decent (not super good), expected for multinomial variables
grid.best_score_

# address for best model
best_model = grid.best_estimator_

# get coefficients of best model
coefs = best_model.named_steps["logisticregression"].coef_
feature_names = best_model.named_steps["columntransformer"].get_feature_names_out()
classes = best_model.named_steps["logisticregression"].classes_
DataFrame(coefs,columns=feature_names,index=classes)

"""**Interpreting the Coefficents**

Primary Research Question: What variables are associated with the validity of a political statement?

- Below is a list of interpreted coefficients that are highly associated with the validity of a political statement (based on the data):

OneHotEncoded Vars: Compared to the reference category, this category increases/decreases log-odds of class X.

StandardScaler Vars: Increasing the X variable increases the log-odds of that specific class relative to the others.

**Track Records**

1. True: Strongly increases log-odds of being classified as True. Strongly decreases log-odds of being classified as Half-True. A strong positive predictor of the "True" class.

2. Half-True: Very strongly increases log-odds of Half-True. Strongly decreases log-odds of True. half_true is the strongest predictor of the Half-True class.

3. False: Moderately increases log-odds of False. Is the strongest predictor of False class.

**Political Party**

4. Party-Republican: Compared to Democrats, republican statements have higher log-odds of being classified as False by 0.206 (1.23 in odds terms) Republican statements have about 20% lower odds of being classified as True compared to Democrat statements.

5. Party-Other: Not super informative

**Topic**

6. False Class: Statements about Healthcare have about 43% higher odds of being classified as False compared to the topic of Economy/Fiscal, holding other variables constant. Statements about Elections/Governance have about 29% higher odds of being classified as False compared to the topic of economy/fiscal, holding other variables constant. Statements about Social Issues have about 27% higher odds of being classified as False compared to the topic of economy/fiscal, holding other variables constant.

7. True Class: Healthcare statements have about 24% lower odds of being classified as True compared to the topic of economy, holding other variables constant.

**Context**

8. Media: Statements that come from from the media have about a 20% higher odds od being classified as Half-True compared to a context of interviews, holding all other variables constant. We can see similar patterns for Speech in the false (decrease) and in true (increase)

**Occupation**

9. Compared to speakers with a government occupation, the odds of a false statement increase by 20% for a speaker with a non-goverment occupation, holding all other variables constant. Compared to speakers with a government occupation, the odds of a true statement decrease by 16% for a speaker with a non-goverment occupation, holding all other variables constant






"""

# Baselines for Cateogorical Predictors are the first entries
best_model.named_steps["columntransformer"] \
    .named_transformers_["onehotencoder"] \
    .categories_

# Proportion Bar Plot of Statement Validities by Occupation and Political Party (3 variables included)
count_cols = ['false*','half_t*','true*']

df = train[["classification","occupation*","party*"]]

ggplot(data = df, mapping = aes(x = 'classification', fill = 'party*')) +\
geom_bar(position = 'fill', width = 0.5) +\
facet_wrap("occupation*") +\
labs(title = "Proportion of Statement Validities", x = 'Statement Validity', y = 'Proportion', subtitle = 'by occupation and political party') +\
scale_fill_manual(values=["#4E79A7", "#76B7B2", "#E15759"])

# Another plot that was not used in the poster
import pandas as pd
import numpy as np
from plotnine import *

count_cols = ['false*','half_t*','true*']

plot_df = melt(
    train,
    id_vars = ['context*','occupation*','party*','topic*'],
    value_vars = count_cols,
    var_name = "truth_type",
    value_name = "count"
)

(
     ggplot(plot_df, aes(x="truth_type", y="count", fill="party*"))
    + stat_summary(fun_y = np.mean, geom="bar", position="dodge")
    + facet_wrap("occupation*")
    + labs(
        x="Truth Category Count",
        y="Average Count",
        title="Distribution of Truthfulness by Political Party/Occupation Type"
    )
    + theme_bw()
    + scale_fill_manual(values=["#4E79A7", "#76B7B2", "#E15759"])
)

"""**Research Question 2**"""

df = concat([train, test])

fakes = ['total-lie', 'false', 'barely-t']
df['fake'] = df['classification'].isin(fakes).astype(int)

df["text"] = df["statement"].astype(str)
df["exclamations"] = df["text"].str.count(r"!") # "r" syntax for raw string,
# not using the jsons, just the shortened statements
# will need to write a function to read each json
df["questions"] = df["text"].str.count(r"\?")
df["word_count"] = df["text"].str.split().apply(len)
# testing with just punctuation for now, but will use targeted words in the proj

vec = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1,2)
)

X = vec.fit_transform(df["statement"])

y = df["fake"]

model = LogisticRegression(max_iter=2000)
model.fit(X, y)

df.groupby("fake")[["exclamations","questions","word_count"]].mean()

import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from textblob import TextBlob
import nltk
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

df = concat([train, test])

# divide labels into two
fakes = ['total-lie', 'false', 'barely-t']
df['fake'] = df['classification'].isin(fakes).astype(int)


## Creating features that display the counts of
## adj, verb, noun
def count_pos(text):
    blob = TextBlob(str(text))

    adj_count = 0
    noun_count = 0
    verb_count = 0

    for word, tag in blob.tags:
        if tag.startswith("JJ"):
            adj_count += 1
        elif tag.startswith("NN"):
            noun_count += 1
        elif tag.startswith("VB"):
            verb_count += 1

    return pd.Series([adj_count, noun_count, verb_count])


df["statement_clean"] = df["statement"].fillna("")


df[["adj_count","noun_count","verb_count"]] = df["statement_clean"].apply(count_pos)

avec = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1,2),
    min_df=3
)

X = avec.fit_transform(df["statement_clean"])
y = df["fake"]

model = LogisticRegression(max_iter=2000)
model.fit(X, y)
tfidf_df = pd.DataFrame(
    X.toarray(),
    columns=avec.get_feature_names_out()
)

from nltk import pos_tag
## extract words and coefficients
word_types = avec.get_feature_names_out()
coef = model.coef_[0]

# Convert to df
coef_df = pd.DataFrame({
    "word": word_types,
    "coef": coef
})

## Positive Coefficients --> closer to +1 indicate fake news
fake_words = coef_df.sort_values("coef", ascending=False).head(200)

## Classify extracted words by POS tagging
def map_pos(tag):
    if tag.startswith("NN"):
        return "noun"
    elif tag.startswith("VB"):
        return "verb"
    elif tag.startswith("JJ"):
        return "adj"
    else:
        return None


fake_words["pos"] = [map_pos(pos_tag([w])[0][1]) for w in fake_words["word"]]


fake_words_filtered = fake_words[fake_words["pos"].notna()]

### Create top 10 most frequent words for nouns/verbs/adj
top_n = 10

top_nouns = (
    fake_words_filtered[fake_words_filtered["pos"] == "noun"]
    .sort_values("coef", ascending=False)
    .head(top_n)
    .reset_index(drop=True)
)

top_verbs = (
    fake_words_filtered[fake_words_filtered["pos"] == "verb"]
    .sort_values("coef", ascending=False)
    .head(top_n)
    .reset_index(drop=True)
)

top_adjs = (
    fake_words_filtered[fake_words_filtered["pos"] == "adj"]
    .sort_values("coef", ascending=False)
    .head(top_n)
    .reset_index(drop=True)
)


print("Top 10 Nouns associated with Fake News")
print(top_nouns[["word","coef"]])

print("Top 10 Verbs associated with Fake News")
print(top_verbs[["word","coef"]])

print("Top 10 Adjectives associated with Fake News")
print(top_adjs[["word","coef"]])

## Repeat for real news -- coeffs closer to -1 indicate true
real_words = coef_df.sort_values("coef", ascending=True).head(200)
def map_pos(tag):
    if tag.startswith("NN"):
        return "noun"
    elif tag.startswith("VB"):
        return "verb"
    elif tag.startswith("JJ"):
        return "adj"
    else:
        return None

real_words["pos"] = [map_pos(pos_tag([w])[0][1]) for w in real_words["word"]]

real_words_filtered = real_words[real_words["pos"].notna()]

top_n = 10

top_nouns_real = (
    real_words_filtered[real_words_filtered["pos"] == "noun"]
    .sort_values("coef")
    .head(top_n)
    .reset_index(drop=True)
)

top_verbs_real = (
    real_words_filtered[real_words_filtered["pos"] == "verb"]
    .sort_values("coef")
    .head(top_n)
    .reset_index(drop=True)
)

top_adjs_real = (
    real_words_filtered[real_words_filtered["pos"] == "adj"]
    .sort_values("coef")
    .head(top_n)
    .reset_index(drop=True)
)

print("Top 10 Nouns associated with True News")
print(top_nouns_real[["word","coef"]])

print("Top 10 Verbs associated with True News")
print(top_verbs_real[["word","coef"]])

print("Top 10 Adjectives associated with True News")
print(top_adjs_real[["word","coef"]])

# Plot top 10 w/ bar charts
top_n = 10

top_nouns_fake_plot = top_nouns.head(top_n).copy()
top_verbs_fake_plot = top_verbs.head(top_n).copy()
top_adjs_fake_plot  = top_adjs.head(top_n).copy()


top_nouns_fake_plot['POS'] = 'Noun'
top_verbs_fake_plot['POS'] = 'Verb'
top_adjs_fake_plot['POS']  = 'Adj'


top_words_fake_plot = pd.concat([top_nouns_fake_plot,
                                 top_verbs_fake_plot,
                                 top_adjs_fake_plot]).reset_index(drop=True)


(ggplot(top_words_fake_plot, aes(x='reorder(word, coef)', y='coef', fill='POS'))
 + geom_col()
 + coord_flip()
 + facet_wrap('~POS', scales='free_y')  # "free_y" separates by POS
 + labs(x='Word', y='Coefficient',
        title='Top 10 Words per POS in Fake Statements',
        subtitle="POS = Parts of Speech")
 + theme_minimal()
 + theme(axis_text_x=element_text(rotation=45))
)

top_nouns_real_plot = top_nouns_real.head(top_n).copy()
top_verbs_real_plot = top_verbs_real.head(top_n).copy()
top_adjs_real_plot  = top_adjs_real.head(top_n).copy()

# Add POS column
top_nouns_real_plot['POS'] = 'Noun'
top_verbs_real_plot['POS'] = 'Verb'
top_adjs_real_plot['POS']  = 'Adj'

# Combine into one dataframe
top_words_real_plot = pd.concat([top_nouns_real_plot,
                                 top_verbs_real_plot,
                                 top_adjs_real_plot]).reset_index(drop=True)

# Faceted bar chart
(ggplot(top_words_real_plot, aes(x='reorder(word, coef)', y='coef', fill='POS'))
 + geom_col()
 + coord_flip()
 + facet_wrap('~POS', scales='free_y')  # separates Noun / Verb / Adj
 + labs(x='Word', y='Coefficient',
        title='Top 10 Words per POS Predicting Real Statements',
        subtitle="POS = Parts of Speech")
 + theme_minimal()
 + theme(axis_text_x=element_text(rotation=45))
)
